SELECT
Id
,IsDeleted
,MasterRecordId
,Name
,Type
,ParentId
,BillingStreet
,BillingCity
,BillingState
,BillingPostalCode
,BillingCountry
,BillingLatitude
,BillingLongitude
,ShippingStreet
,ShippingCity
,ShippingState
,ShippingPostalCode
,ShippingCountry
,ShippingLatitude
,ShippingLongitude
,AccountNumber
,Industry
,AnnualRevenue
,NumberOfEmployees
,Ownership
,TickerSymbol
,Description
,Site
,CurrencyIsoCode
,OwnerId
,CreatedDate
,CreatedById
,LastModifiedDate
,LastModifiedById
,SystemModstamp
,DunsNumber
,NaicsCode
,NaicsDesc
,Sales_Team_Assigned__c
,VAT_Number__c
,Primary_US_SIC_Code__c
,Doing_Business_As__c
,Latest_Annual_Revenue__c
,Revenue__c
,Net_Income__c
,Net_Income_Growth__c
,Employees_at_this_Location__c
,US_Ticker_Symbol__c
,CSR_Date__c
,Region__c
,Oracle_AccountID__c
,SFDC_Account_ID__c
,Address1_Line_1__c
,Address1_Line_2__c
,Address1_Line_3__c
,City1__c
,State1__c
,Zip_Code1__c
,Country1__c
,Address2_Line_1__c
,Address2_Line_2__c
,Address2_Line_3__c
,City2__c
,Country2__c
,State2__c
,Zip_Code2__c
,Office__c
,HooversId__c
,D_U_N_S__c
,Total_Invoice_Amount__c
,Terms_Of_Sale__c
,Sales_Channel__c
,Oracle_PartyID__c
,K_Date__c
,Prior_Sales_Team__c
,K_Information__c
,Sales_Team_Name__c
,Acc18ID__c
,ORS_Ownership_Date__c
,ORS__c
,Fortune_500__c
FROM
Account
WHERE
CreatedDate >= :Start
and CreatedDate <= :End
